mode:
  local:
    template: "./submit/templates/local_job_cmd.j2"
    runtime: "venv"
    shell_executable: "bash"
  cloud_local:
    template: "./submit/templates/cloud_local_job_cmd.j2"
    runtime: "conda"
    shell_executable: "bash"
  slurm:
    template: "./submit/templates/slurm_job.sh.j2"
    runtime: "singularity"

runtime:
  venv:
    python_cmd: "./.venv/bin/python"
  conda:
    python_cmd: "python"
    pre_command: |
      eval "$(conda shell.bash hook)"
      conda activate nosplace-py311
  singularity:
    python_cmd: "python"
    command_wrapper: "singularity exec --bind /mnt:/mnt --nv python.sif bash -lc"

scripts:
  fit_prior_ood:
    path: "./luno_experiments/scripts/fit.py"
    default_args:
      data_name: ["pos_2", "pos_neg_2", "pos_neg_flip_2", "base_2", "flip_2"]
      max_iter: 40
      num_samples: 40
      spatial_kernel_expr: ["'m12 + m32 + m52 + m72 + rq'", "'m12 + m32 + m52 + m72 + rq + rq + rq'", "'m12 + m32 + m32 + m32'"]
      function_kernel_expr: ["'h1 + sm32 + sm32 + sm32'", "'h1 + sm32 + sm52 + sm72 + sm72'", "'h1 + sm12 + sm52 + sm72 + sqr + sqr'", "'h1 + sqr + sqr + sqr'"]
