mode:
  slurm:
    template: "./submit/templates/slurm_job.sh.j2"
    pykernel: ""
    pre_command: |
      eval "$(conda shell.bash hook)"
      conda activate nosplace-py311

scripts:
  train_luno_apebench:
    path: "./luno_experiments/scripts/train.py"
    default_args:
      mode: "luno"
      data_name: ["diff_diff_1", "diff_lin_1", "diff_ks_cons_1", "diff_hyp_diff_1", "diff_burgers_1"]
      seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      num_train_samples: 100
      batch_size: 32
      learning_rate: 0.001
      weight_decay: 0.0001
      num_epochs: 1000
  
  train_fsp_apebench:
    path: "./luno_experiments/scripts/train.py"
    default_args:
      mode: "fsp"
      data_name: ["diff_diff_1", "diff_lin_1", "diff_ks_cons_1", "diff_hyp_diff_1", "diff_burgers_1"]
      seed: [0, 1, 2, 3]
      num_train_samples: 100
      batch_size: 32
      learning_rate: 0.001
      weight_decay: 0.0001
      num_epochs: 1000
      num_spatial_subsample: 1
      context_strategy: "gp"
      context_kernel: ["m32", "m52", "rbf"]
      grid_stride: [4, 8, 2, 1]
      prior_name: ["'c28ad71f'", "'d48291a7'", "'0837b60f'", "'281d74e8'", "'8795269a'"]
